// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsLetterBoy.Repository;

namespace NewsLetterBoy.Repository.Migrations
{
    [DbContext(typeof(NewsLetterDbContext))]
    [Migration("20220120181915_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewsLetterBoy.Model.NewsLetter.NewsLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsLetters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 1, 20, 21, 49, 14, 376, DateTimeKind.Local).AddTicks(9815),
                            Description = "About information technologies an data science",
                            IsDeleted = false,
                            Title = "Tech news"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 1, 20, 21, 49, 14, 389, DateTimeKind.Local).AddTicks(2393),
                            Description = "About Science and academic research",
                            IsDeleted = false,
                            Title = "Science news"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 1, 20, 21, 49, 14, 389, DateTimeKind.Local).AddTicks(2454),
                            Description = "About cryptocurrencies and economy",
                            IsDeleted = false,
                            Title = "Financial news"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 1, 20, 21, 49, 14, 389, DateTimeKind.Local).AddTicks(2461),
                            Description = "About Sport and fitness around the world",
                            IsDeleted = false,
                            Title = "Sport news"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 1, 20, 21, 49, 14, 389, DateTimeKind.Local).AddTicks(2465),
                            Description = "About industrial and engineering",
                            IsDeleted = false,
                            Title = "Technology news"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 1, 20, 21, 49, 14, 389, DateTimeKind.Local).AddTicks(2479),
                            Description = "About politics ",
                            IsDeleted = false,
                            Title = "Political news"
                        });
                });

            modelBuilder.Entity("NewsLetterBoy.Model.Subscription.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewsLetterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubscriptionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
